name: Java Tests (JUnit 5)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download JUnit Console
        run: |
          curl -L -o junit-platform-console-standalone.jar \
          https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.3/junit-platform-console-standalone-1.10.3.jar

      - name: Compile
        run: |
          find . -name "*.java" > sources.txt
          javac -cp ".:junit-platform-console-standalone.jar" @sources.txt

      - name: Run tests
        run: |
          java -jar junit-platform-console-standalone.jar \
            --class-path . \
            --scan-class-path
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Clean old class files
        run: find . -name "*.class" -delete

      - name: Compile main code
        run: |
          find ./main -name "*.java" > mainsources.txt
          javac @mainsources.txt

      - name: Create JAR
        run: |
          jar cfe MyGame.jar main.my2dgame -C . .

      - name: Upload Artifact (Deployment)
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-Build
          path: MyGame.jar